steps:
  - name: "bash"
    args: ["echo", "Hello, World!"]
  - name: "bash"
    args: ["pwd"]
  - name: "bash"
    args: ["ls", "-al"]
  - name: "bash"
    args: ["touch", "building.txt"]
  - name: "bash"
    args: ["ls", "-al"]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/practice/python-image:latest', '.' ]
  images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/practice/python-image:latest'

  timeout: 500s
  options:
    logging: CLOUD_LOGGING_ONLY #サービスアカウントを指定するので、ログ保存先を制限
