steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/practice/python-image:$COMMIT_SHA', '.' ]

    # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast1-docker.pkg.dev/$PROJECT_ID/practice/python-image:$COMMIT_SHA']

  # Artifact RegistryのコンテナイメージをCloud Runにデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "p-python"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/practice/python-image:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
  
  images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/practice/python-image:$COMMIT_SHA'

  - name: "bash"
    args: ["echo", "Hello, World!"]
  - name: "bash"
    args: ["pwd"]
  - name: "bash"
    args: ["ls", "-al"]
  - name: "bash"
    args: ["touch", "building.txt"]
  - name: "bash"
    args: ["ls", "-al"]

  timeout: 500s
  options:
    logging: CLOUD_LOGGING_ONLY #サービスアカウントを指定するので、ログ保存先を制限
