// develop.yml

name: develop

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  SERVICE: p-python
  REGION: asia-northeast1
  IMAGE: asia-northeast1-docker.pkg.dev/cloud-run-source-deploy/${{ secrets.GCP_PROJECT }}/p-python
  TAG: develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker Authorize
        run: gcloud auth configure-docker

      - name: Docker Build and Push
        run: |
          docker build \
            -f Dockerfile \
            --build-arg BUILD_ID=$BUILD_ID \
            -t ${{ env.IMAGE }}:${{ github.sha }} \
            -t ${{ env.IMAGE }}:latest .
      - name: Publish
        run: |
          docker push ${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.IMAGE }}:${{ github.sha }} \
            --project ${{ env.PROJECT_ID }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --no-traffic \
            --tag ${{ env.TAG }}